export const URL_SETTINGS = "/settings";

// SYSTEM SETTINGS URL
export const URL_SYSTEM_SETTINGS = "/settings/system",
  URL_SYSTEM_SETTINGS_GENERAL = URL_SYSTEM_SETTINGS + "/general",
  URL_SYSTEM_SETTINGS_TRACKING_DOMAINS =
    URL_SYSTEM_SETTINGS + "/tracking-domains",
  URL_SYSTEM_SETTINGS_URLS = URL_SYSTEM_SETTINGS + "/urls",
  URL_SYSTEM_SETTINGS_EMAIL = URL_SYSTEM_SETTINGS + "/email",
  URL_SYSTEM_SETTINGS_TRAFFICBACK = URL_SYSTEM_SETTINGS + "/trafficback",
  URL_SYSTEM_SETTINGS_SECURITY = URL_SYSTEM_SETTINGS + "/security",
  URL_SYSTEM_SETTINGS_OFFERS_TRACKING_DOMAINS =
    URL_SYSTEM_SETTINGS + "/offers-tracking-domains";

// CONTENT SETTINGS URL
export const URL_CONTENT_SETTINGS = "/settings/content",
  URL_CONTENT_SETTINGS_PAGES = URL_CONTENT_SETTINGS + "/pages",
  URL_CONTENT_SETTINGS_PAGES_$ID_CATEGORY_$ID =
    URL_CONTENT_SETTINGS + "/pages/:idPages/categories/:idCategory",
  URL_CONTENT_SETTINGS_PAGES_ID_CATEGORY_ID = (
    idPages: number | string,
    idCategory: string = "new"
  ) => {
    return URL_CONTENT_SETTINGS + `/pages/${idPages}/categories/${idCategory}`;
  },
  URL_CONTENT_SETTINGS_CATEGORIES = URL_CONTENT_SETTINGS + "/categories",
  URL_CONTENT_SETTINGS_GOALS = URL_CONTENT_SETTINGS + "/goals",
  URL_CONTENT_SETTINGS_CURRENCIES = URL_CONTENT_SETTINGS + "/currencies",
  URL_CONTENT_SETTINGS_PAYMENT_SYSTEM =
    URL_CONTENT_SETTINGS + "/payment-systems",
  URL_CONTENT_SETTINGS_EMAIL_TEMPLATES =
    URL_CONTENT_SETTINGS + "/email-templates",
  URL_CONTENT_SETTINGS_TRAFFIC_SOURCES =
    URL_CONTENT_SETTINGS + "/traffic-sources",
  URL_CONTENT_SETTINGS_OFFERS_DESCRIPTION_TEMPLATES =
    URL_CONTENT_SETTINGS + "/offers-description-templates",
  URL_CONTENT_SETTINGS_OFFERS_KPI_TEMPLATES =
    URL_CONTENT_SETTINGS + "/offers-kpi-templates",
  URL_CONTENT_SETTINGS_OFFERS_GOAL_TEMPLATES =
    URL_CONTENT_SETTINGS + "/offer-goal-template";
export const URL_CONTENT_SETTINGS_INVOICES_PAYMENT_SYSTEM =
    URL_CONTENT_SETTINGS + "/invoices-payment-systems",
  URL_CONTENT_SETTINGS_TAGS = URL_CONTENT_SETTINGS + "/tags",
  URL_CONTENT_SETTINGS_REPORTING_LINKS =
    URL_CONTENT_SETTINGS + "/reportings-links",
  URL_CONTENT_SETTINGS_TOP_OFFERS = URL_CONTENT_SETTINGS + "/top-offers",
  URL_CONTENT_SETTINGS_TICKETS_CATEGORIES =
    URL_CONTENT_SETTINGS + "/tickets-categories",
  URL_CONTENT_SETTINGS_MESSENGER = URL_CONTENT_SETTINGS + "/messengers";

// AFFILIATE DASHBOARD DESIGN
export const URL_SETTINGS_DASHBOARD = "/settings/affiliate-dashboard-design",
  URL_SETTINGS_DASHBOARD_GENERAL = URL_SETTINGS_DASHBOARD + "/general",
  URL_SETTINGS_DASHBOARD_REGISTRATION =
    URL_SETTINGS_DASHBOARD + "/registration",
  URL_SETTINGS_DASHBOARD_SUPPORT_INFORMATION =
    URL_SETTINGS_DASHBOARD + "/support-information",
  URL_SETTINGS_DASHBOARD_DOCUMENTS = URL_SETTINGS_DASHBOARD + "/documents";
