import {
  URL_CONTENT_SETTINGS_CATEGORIES,
  URL_CONTENT_SETTINGS_CURRENCIES,
  URL_CONTENT_SETTINGS_EMAIL_TEMPLATES,
  URL_CONTENT_SETTINGS_GOALS,
  URL_CONTENT_SETTINGS_INVOICES_PAYMENT_SYSTEM,
  URL_CONTENT_SETTINGS_MESSENGER,
  URL_CONTENT_SETTINGS_OFFERS_DESCRIPTION_TEMPLATES,
  URL_CONTENT_SETTINGS_OFFERS_GOAL_TEMPLATES,
  URL_CONTENT_SETTINGS_OFFERS_KPI_TEMPLATES,
  URL_CONTENT_SETTINGS_PAGES,
  URL_CONTENT_SETTINGS_PAYMENT_SYSTEM,
  URL_CONTENT_SETTINGS_REPORTING_LINKS,
  URL_CONTENT_SETTINGS_TAGS,
  URL_CONTENT_SETTINGS_TICKETS_CATEGORIES,
  URL_CONTENT_SETTINGS_TOP_OFFERS,
  URL_CONTENT_SETTINGS_TRAFFIC_SOURCES,
} from "Constants/URLConstants/URLCabinet/URLSettings";

const CONTENT_SETTINGS_URL = [
  {
    title: "Pages",
    to: URL_CONTENT_SETTINGS_PAGES,
    includes: URL_CONTENT_SETTINGS_PAGES,
  },
  {
    title: "Categories",
    to: URL_CONTENT_SETTINGS_CATEGORIES,
    includes: URL_CONTENT_SETTINGS_CATEGORIES,
  },
  {
    title: "Goals",
    to: URL_CONTENT_SETTINGS_GOALS,
    includes: URL_CONTENT_SETTINGS_GOALS,
  },
  {
    title: "Currencies",
    to: URL_CONTENT_SETTINGS_CURRENCIES,
    includes: URL_CONTENT_SETTINGS_CURRENCIES,
  },
  {
    title: "Payment systems",
    to: URL_CONTENT_SETTINGS_PAYMENT_SYSTEM,
    includes: URL_CONTENT_SETTINGS_PAYMENT_SYSTEM,
  },
  {
    title: "Email templates",
    to: URL_CONTENT_SETTINGS_EMAIL_TEMPLATES,
    includes: URL_CONTENT_SETTINGS_EMAIL_TEMPLATES,
  },
  {
    title: "Traffic sources",
    to: URL_CONTENT_SETTINGS_TRAFFIC_SOURCES,
    includes: URL_CONTENT_SETTINGS_TRAFFIC_SOURCES,
  },
  {
    title: "Offers Description templates",
    to: URL_CONTENT_SETTINGS_OFFERS_DESCRIPTION_TEMPLATES,
    includes: URL_CONTENT_SETTINGS_OFFERS_DESCRIPTION_TEMPLATES,
  },
  {
    title: "Offers KPI templates",
    to: URL_CONTENT_SETTINGS_OFFERS_KPI_TEMPLATES,
    includes: URL_CONTENT_SETTINGS_OFFERS_KPI_TEMPLATES,
  },
  {
    title: "Offers Goal templates",
    to: URL_CONTENT_SETTINGS_OFFERS_GOAL_TEMPLATES,
    includes: URL_CONTENT_SETTINGS_OFFERS_GOAL_TEMPLATES,
  },
  {
    title: "Invoices Payment systems",
    to: URL_CONTENT_SETTINGS_INVOICES_PAYMENT_SYSTEM,
    includes: URL_CONTENT_SETTINGS_INVOICES_PAYMENT_SYSTEM,
  },
  {
    title: "Tags",
    to: URL_CONTENT_SETTINGS_TAGS,
    includes: URL_CONTENT_SETTINGS_TAGS,
  },
  {
    title: "Reporting links",
    to: URL_CONTENT_SETTINGS_REPORTING_LINKS,
    includes: URL_CONTENT_SETTINGS_REPORTING_LINKS,
  },
  {
    title: "TOP offers",
    to: URL_CONTENT_SETTINGS_TOP_OFFERS,
    includes: URL_CONTENT_SETTINGS_TOP_OFFERS,
  },
  {
    title: "Tickets Categories",
    to: URL_CONTENT_SETTINGS_TICKETS_CATEGORIES,
    includes: URL_CONTENT_SETTINGS_TICKETS_CATEGORIES,
  },
  {
    title: "Messengers",
    to: URL_CONTENT_SETTINGS_MESSENGER,
    includes: URL_CONTENT_SETTINGS_MESSENGER,
  },
];

export default CONTENT_SETTINGS_URL;
